batch_size : 10
num_workers : 4
data_dir : "datasets\\base_Annual\\MSI_Annual_256"
bands : [0, 1, 2, 3, 4, 5, 6, 7, 8] #9channels for MSI
threshold : 0.015
manual_split : False
patch_size : 256
eval_lakes : []