batch_size : 8
num_workers : 4
data_dir : "datasets\\base_Annual\\MSI_Annual_256" #can also work with MSI datasets? Check later
bands : [0, 1, 2]
threshold : 0.015
manual_split : False
patch_size : 256